GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoibWFyc2VsIiwidXNlckVtYWlsIjoibWFyc2VsQGdtYWlsLmNvbSIsImlhdCI6MTc0MTc2NDc3NiwiZXhwIjoxNzQxNzY0ODI2fQ.SBY29EF2R0uQoXt7cP5qUQE7pqbo58p5wa3HoFOk9d8

###
POST http://localhost:5000/users/register
Content-Type: application/json

# {
#     "username": "marsel",
#     "email": "marsel@gmail.com",
#     "password": "marsel",
#     "confirmPassword": "marsel"
# }
{
    "username": "panjul",
    "email": "panjul@gmail.com",
    "password": "panjul",
    "confirmPassword": "panjul"
}

###
DELETE http://localhost:5000/users/15

###
POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "marsel@gmail.com",
    "password": "marsel"
}

# {
#     "email": "admin@gmail.com",
#     "password": "admin"
# }


